#!/bin/bash

BOUNDARYNAME=$1


if [ -z "$1" ]
then
echo
echo
echo 'computes a binarized convexity map for surface visualization'
echo
echo
echo 'Inputs:'
echo 'BOUNDARYNAME=$1, e.g. boundary05, generated by generateSurfaces.sh, the parent of the inflated surface'
exit 1
fi


Rscript $AFNI_TOOLBOXDIR/surfaces/binarizedConv.R \
 $BOUNDARYNAME