args <- commandArgs(T)
print( args )
# takes a 1D roi file generated by afni, removes the comments and the column of 1s,
# saves an roi.temp file with only the roi vertex index for further processing in AFNI

tempName <- sprintf( '%s.temp', args[1] )
roiData <- read.table( args[1], comment.char='#' )
write.table( roiData[,1], file=tempName, col.names=FALSE, row.names=FALSE )