#!/bin/bash

BOUNDARYTHR=$1
SMOOTHPAR=$2
INFLATESURFACES=$3
INFLATEITERATIONS=$4
REMESHFRACTION=$5

if [ -z "$1" ]
then
echo
echo
echo 'generates the surfaces starting from a boundaries volume'
echo 'see defineBoundaries.sh for that'
echo
echo 'Inputs:'
echo 'BOUNDARYTHR=$1, e.g. boundariesThr.nii.gz, generated by defineBoundaries.sh'
echo 'SMOOTHPAR=$2, slightly smooth the surfaces (must be an even number, try something like 46)'
echo 'INFLATESURFACES=$3, which surfaces to inflate must be in this form: 1-3-5 or 0-3-7, afni starts counting from zero, and I follow the same'
echo 'rule when I numebr the surfaces'
echo 'INFLATEITERATIONS=$4, how many interations for inflation? e.g. 800'
echo 'REMESHFRACTION=$5, while remeshing, which proportion of nodes you want to keep, e.g. 0.95'
echo
echo
exit 1
fi


Rscript $AFNI_TOOLBOXDIR/surfaces/generateSurfacesFromBoundaries.R \
$BOUNDARYTHR \
$SMOOTHPAR \
$INFLATESURFACES \
$INFLATEITERATIONS \
$REMESHFRACTION

