#!/bin/bash

BOUNDARYNAME=$1
ROIFILE=$2
SURFACEDIR=$3
DIAMETER=$4
OUTPUTNAME=$5

if [ -z "$1" ]
then
echo
echo 'fills a SUMA surface ROI, defined with lines over an area '
echo
echo 'Inputs:'
echo 'BOUNDARYNAME=$1, e.g. boundary05, generated by generateSurfaces.sh'
echo 'ROIFILE=$2, SUMA surface roi in 1D.roi format e.g. test.1D.roi'
echo 'SURFACEDIR=$3, directory where surfaces are stored, with backslash, e.g surfaces_folder_right/'
echo 'DIAMETER=$4, filling diameter in mm, e.g. 2' 
echo 'OUTPUTNAME=$5, ourput name in SUMA surface roi format e.g. outFilled.1D.roi'
echo
exit 1
fi


Rscript $AFNI_TOOLBOXDIR/surfaces/getRoiFromSurface.R \
 $BOUNDARYNAME \
 $ROIFILE \
 $SURFACEDIR \
 $DIAMETER \
 $OUTPUTNAME
