#!/bin/bash

ROINAME=$1
THRESHOLD=$2
BOUNDARY=$3
DIRECTORYSURFACESFILE=$4
COLUMNINDEXSURFACES=$5
DOWNSAMPLINGFACTOR=$6
FILENAMEOUT=$7
SMOOTHINGPAR=$8

if [ -z "$1" ]
then

echo
echo
echo 'computes a distance map with respect to a boundary defined by the threshold value provided,'
echo 'useful for PSF estimation over the surface (stripes data)'
echo
echo
echo 'Inputs:'
echo 'ROINAME=$1, e.g. roiname defined around the boundary'
echo 'THRESHOLD=$2, e.g. threshold over which the boundary is defined'
echo 'BOUNDARY=$3, e.g. boundary05, generated by generateSurfaces.sh'
echo 'DIRECTORYSURFACESFILE=$4, directory where the surfaces are projected, probably you want to smooth heavily too'
echo 'COLUMNINDEXSURFACES=$5, column index of interest from the surfaces file'
echo 'DOWNSAMPLINGFACTOR=$6, downsampling factor to compute distances, the higher, the faster (e.g. 8)'
echo 'FILENAMEOUT=$7, filename prefix for output'
echo 'SMOOTHINGPAR=$8, smoothing distance map over the surface to account for downsampling (in mm)'
echo
echo 'example call localDistanceFromBoundary.sh V2DorsalLeft_filled_interp_surfaces_folder/roiOut_0_filled.1D.roi 0 boundary00 phaseSpecCohMax_interp_surfaces_folder/boundary00_sm_phaseSpecCohMax_surf.1D.dset 7 8 V2DorsalLeft_filled 1'

exit 1
fi


Rscript $AFNI_TOOLBOXDIR/surfaces/localDistanceFromBoundary_test.R \
$ROINAME \
$THRESHOLD \
$BOUNDARY \
$DIRECTORYSURFACESFILE \
$COLUMNINDEXSURFACES \
$DOWNSAMPLINGFACTOR \
$FILENAMEOUT \
$SMOOTHINGPAR \
$AFNI_INSTALLDIR \
$AFNI_TOOLBOXDIR
