#!/bin/bash

BOUNDARYNAME=$1
DISTANCEROI=$2
PARENTVOLUME=$3
DEPTH=$4

if [ -z "$1" ]
then
echo
echo
echo 'computes a distance map over an ROI for details see tutorial .... (toDo)'
echo
echo
echo 'Inputs:'
echo 'BOUNDARYNAME=$1, e.g. boundary05, generated by generateSurfaces.sh'
echo 'DISTANCEROI=$2, e.g. 1D roi created following the tutorial ... (toDo)'
echo 'PARENTVOLUME=$3, e.g. anatomy_N3.nii.gz, the anatomy where the surfaces are projected'
echo 'DEPTH=$4, e.g. continous_depth.nii.gz, from MIPAV'
exit 1
fi


Rscript $AFNI_TOOLBOXDIR/surfaces/localDistanceMap.R \
 $BOUNDARYNAME \
 $DISTANCEROI \
 $PARENTVOLUME \
 $DEPTH \
 $AFNI_INSTALLDIR \
 $AFNI_TOOLBOXDIRSURFACES

