args <- commandArgs(T)
print( args )

maxInd <- function(inputVec) { # function to select vertices from map data
  mIndex <- which( inputVec==max(inputVec) )
  mIndexClean <- mIndex[1]
  return( mIndexClean )
}

## debug:
#setwd('/media/alessiofracasso/storage2/dataLaminar_leftVSrightNEW/V2677leftright_Ric/resultsCBS')
#args<-c('rightV1.1D.roi', 5)

argSplit <- strsplit(args[1],'[.]')
fileBase <- argSplit[[1]][1]

## checkdir, create if it does not exists, if it exists then halts execution
mainDir <- getwd()
subDir <- sprintf( '%s_folder', fileBase )
flagDir <- dir.create( file.path(mainDir, subDir) )
if (flagDir==FALSE) { # directory already exists!
  msg <- sprintf( 'Remove the directory %s_folder to proceed', fileBase )
  warning( msg )
  stopifnot(flagDir)  
}

## back to main directory
setwd( file.path(mainDir) )

flagCSF <- 1 # 0 for debugging purposes
if (flagCSF==1) {
  ##############################################################################
  ## creates mapping and rois over the surfaces, sequentially towards the CSF ##
  ##############################################################################
  
  # takes a 1D roi file generated by afni, removes the comments and the column of 1s,
  # saves an roi file with only the roi vertex index for further processing in AFNI
  startSurface <- as.numeric(args[2])
  if (startSurface<10) { roiSurfacesName <- sprintf( 'roiSurface_%s_0%s_%s.1D.roi', fileBase, startSurface, startSurface+1 ) }
  if (startSurface>=10) { roiSurfacesName <- sprintf( 'roiSurface_%s_%s_%s.1D.roi', fileBase, startSurface, startSurface+1 ) }  
  roiData <- read.table( args[1], comment.char='#' )
  write.table( roiData[,1], file=roiSurfacesName, col.names=FALSE, row.names=FALSE )
  
  ## select coords ad topo files
  setwd( sprintf( '%s/surfaces_folder', mainDir)  )
    coordFiles <- dir(pattern='^boundary.*coord')
    topoFiles <- dir(pattern='^boundary.*topo')
  setwd( mainDir  )
  
  ## loop through the surfaces, towards the CSF
  for ( k in (startSurface+1) : (length( coordFiles )-1) ) { #because files starts form 0
    
    outputFile <- sprintf( 'map_01_%s', roiSurfacesName )
    
    roiData <- read.table( roiSurfacesName ) # in case the node in the destination surface is not connected (-1), then put 1
    fileOutIdx <- which( roiData[,1]==-1 )
    if ( length(fileOutIdx)>0 ) {
      roiData[fileOutIdx,1] <- 1
    }
    write.table( roiData[,1], file=roiSurfacesName, col.names=FALSE, row.names=FALSE )
        
    instr <- sprintf( 'SurfToSurf -i_1D surfaces_folder/%s surfaces_folder/%s -i_1D surfaces_folder/%s surfaces_folder/%s -prefix %s -node_indices %s', 
                      topoFiles[k], coordFiles[k], topoFiles[k+1], coordFiles[k+1], outputFile, 
                      roiSurfacesName )
    
    system( instr ) # create map data
    
    mapData <- read.table( sprintf( '%s%s', outputFile, '.1D' ), comment.char='#' )  #read map data
    
    maxIndArray <- apply( mapData[,5:7], 1, maxInd ) #select vertices indices on surf k+1 from mapData
    appSurfMap <- mapData[,2:4] 
    vertexIndArray <- rep( 0, dim(mapData)[1] )
    for ( n in 1:dim(mapData)[1] ) { #select vertices on surf k+1 from mapData
      vertexIndArray[n] <- appSurfMap[ n, maxIndArray[n] ]  
    }
    
    if (k<10) { roiSurfacesName <- sprintf( 'roiSurface_%s_0%d.1D.roi', fileBase, k )  }
    if (k>=10) { roiSurfacesName <- sprintf( 'roiSurface_%s_%d.1D.roi', fileBase, k )  }
    write.table( vertexIndArray, file=roiSurfacesName, col.names=FALSE, row.names=FALSE )
    
  }
}


flagWM <- 1 # 0 for debugging purposes
if (flagWM==1) {
  #############################################################################
  ## creates mapping and rois over the surfaces, sequentially towards the WM ##
  #############################################################################
  
  # takes a 1D roi file generated by afni, removes the comments and the column of 1s,
  # saves an roi file with only the roi vertex index for further processing in AFNI
  startSurface <- as.numeric(args[2])
  if (startSurface<10) { roiSurfacesName <- sprintf( 'roiSurface_%s_0%s_%s.1D.roi', fileBase, startSurface, startSurface-1 ) }
  if (startSurface>=10) { roiSurfacesName <- sprintf( 'roiSurface_%s_%s_%s.1D.roi', fileBase, startSurface, startSurface-1 ) }
  roiData <- read.table( args[1], comment.char='#' )
  write.table( roiData[,1], file=roiSurfacesName, col.names=FALSE, row.names=FALSE )
  
  ## select coords ad topo files
  setwd( sprintf( '%s/surfaces_folder', mainDir)  )
    coordFiles <- dir(pattern='^boundary.*coord')
    topoFiles <- dir(pattern='^boundary.*topo')
  setwd( mainDir  )
  
  ## loop through the surfaces, towards the WM
  for ( k in (startSurface+1) : 2 ) { #because files starts form 0
    
    outputFile <- sprintf( 'map_01_%s', roiSurfacesName )
    
    roiData <- read.table( roiSurfacesName ) # in case the node in the destination surface is not connected (-1), then put 1
    fileOutIdx <- which( roiData[,1]==-1 )
    if ( length(fileOutIdx)>0 ) {
      roiData[fileOutIdx,1] <- 1
    }
    write.table( roiData[,1], file=roiSurfacesName, col.names=FALSE, row.names=FALSE )
    
    instr <- sprintf( 'SurfToSurf -i_1D surfaces_folder/%s surfaces_folder/%s -i_1D surfaces_folder/%s surfaces_folder/%s -prefix %s -node_indices %s', 
                      topoFiles[k], coordFiles[k], topoFiles[k-1], coordFiles[k-1], outputFile, 
                      roiSurfacesName )
    
    system( instr ) # create map data
    
    mapData <- read.table( sprintf( '%s%s', outputFile, '.1D' ), comment.char='#' )  #read map data
    
    maxIndArray <- apply( mapData[,5:7], 1, maxInd ) #select vertices indices on surf k-1 from mapData
    appSurfMap <- mapData[,2:4] 
    vertexIndArray <- rep( 0, dim(mapData)[1] )
    for ( n in 1:dim(mapData)[1] ) { #select vertices on surf k+1 from mapData
      vertexIndArray[n] <- appSurfMap[ n, maxIndArray[n] ]  
    }
    
    if (k<10) { roiSurfacesName <- sprintf( 'roiSurface_%s_0%d.1D.roi', fileBase, k-2 ) }
    if (k>=10) { roiSurfacesName <- sprintf( 'roiSurface_%s_0%d.1D.roi', fileBase, k-2 ) }
    write.table( vertexIndArray, file=roiSurfacesName, col.names=FALSE, row.names=FALSE )
    
  }
}

## move all the files generated into the subDir
system( sprintf('mv roiSurface*%s*.roi %s', fileBase, subDir) )
system( sprintf('mv map*%s*.M2M %s', fileBase, subDir) )
system( sprintf('mv map_01*%s*.1D %s', fileBase, subDir) )
