#!/bin/bash

#ROINAME='LEFTV1.1D.roi'
#BOUNDARY='boundary05'
#ANAT='anatomy_crop.nii.gz'
#DEPTH='continous_depth.nii.gz'

ROINAME=$1
BOUNDARY=$2
DEPTH=$3
MINCLUSTSIZE=$4
SURFACESFOLDER=$5

if [ -z "$1" ]
then
echo 'computes map ROI in volume space from surface space'
echo 'Inputs:'
echo 'ROINAME=$1, e.g. leftRoi02_axis.dset [with surface indices, x axis ref frame and y axis ref frame]'
echo 'BOUNDARY=$2, e.g. boundary05, generated by generateSurfaces.sh'
echo 'DEPTH=$3, e.g. anatomy_crop.nii.gz'
echo 'MINCLUSTSIZE=$4 minimum cluster size to include in the volume ROI, in voxels, typically ~50'
echo 'SURFACESFOLDER=$5 which surfaces folder for example surfaces_folder_right/, remember to add the backslash!'
exit 1
fi

Rscript $AFNI_TOOLBOXDIR/surfaces/surf2VolRoi_Map.R \
$ROINAME \
$BOUNDARY \
$DEPTH \
$AFNI_INSTALLDIR \
$AFNI_TOOLBOXDIRSURFACES \
$MINCLUSTSIZE \
$SURFACESFOLDER
