#!/bin/bash

BOUNDARYNAME=$1
ROI=$2
NODEFACTR=$3
KERNELRADIUS=$4
SURFACESFOLDER=$5

if [ -z "$1" ]
then
echo
echo
echo 'computes the orthogonal axis representing the flattened mesh'
echo
echo
echo 'Inputs:'
echo 'BOUNDARYNAME=$1, e.g. boundary05, generated by generateSurfaces.sh'
echo 'ROI=$2, e.g. 1D roi '
echo 'NODEFACTR=$3, downsampling factor for the number of nodes, try with 7 to begin with, small number -> longer computation time'
echo 'KERNELRADIUS=$4, radius of the interpolating kernel over the surface, in mm'
echo 'SURFACESFOLDER=$5 surface folder (left or right), remember to include the backslash! for example: surfaces_left/'
echo
exit 1
fi


Rscript $AFNI_TOOLBOXDIR/devel/compSpectralDecompRoi.R \
$BOUNDARYNAME \
$ROI \
$NODEFACTR \
$KERNELRADIUS \
$AFNI_INSTALLDIR \
$AFNI_TOOLBOXDIRSURFACES \
$SURFACESFOLDER


