#!/bin/bash

BOUNDARYNAME=$1
ROI=$2
ROICOLUMN=$3

if [ -z "$1" ]
then
echo
echo
echo 'extracts a patch from a surfaces, returning the coordinates and the topology (vertices and faces) of that patch'
echo
echo
echo 'Inputs:'
echo 'BOUNDARYNAME=$1, e.g. boundary05, generated by generateSurfaces.sh'
echo 'ROI=$2, e.g. 1D roi '
echo 'ROICOLUMN=$3, which ROI column in the ROI contains the nodes indices in the surface, in'
echo 'AFNI format, counting from 0. E.g. if it is the first column, then input 0; 1 for the second column and so forth'
echo
exit 1
fi


Rscript $AFNI_TOOLBOXDIR/surfaces/extractPatch.R \
$BOUNDARYNAME \
$ROI \
$ROICOLUMN
